[package]
name = "lrnrtos"
version = "0.4.0"
edition = "2024"

[[bin]]
name= "lrnrtos"
test = false

[dependencies]
arrayvec = {version = "0.7.6", default-features = false}

[features]
default = ["logs", "kprint"]
logs = []
kprint = []
test = []
