name: Build and test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }} / ${{ matrix.toolchain }}) for target -> $({{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [nightly]
        target: [riscv32imc-unknown-none-elf]

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.toolchain }}-cargo-
    - name: Add target
      run: rustup target add ${{ matrix.target }}
    - name: Add rust-src
      run: rustup component add rust-src --toolchain ${{ matrix.toolchain }}
    - name: Build for target
      run: cargo build --release --target ${{ matrix.target }}
  lint:
    name: Lint and check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly]
        target: [riscv32imc-unknown-none-elf]

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.toolchain }}-cargo-
    - name: Add rustfmt
      run: rustup component add rustfmt --toolchain ${{ matrix.toolchain }}
    - name: Add clippy
      run: rustup component add clippy --toolchain  ${{ matrix.toolchain }}
    - name: Add rust-src 
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy -Zjson-target-spec --target arch/${{ matrix.target }}.json -- -D warnings
  test:
    name: Run kernel in test mode
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (nightly)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src

      - name: Install QEMU (riscv32)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-misc

      - name: Run kernel tests in QEMU
        run: |
          # IMPORTANT: make test must return 0 on success, non-zero on failure.
          make test_build && make
